"""Sensitivity analysis for the study-specific Table 4 screening thresholds.

Uses the analysis tables generated by the main workflow. Each numerical threshold
is varied one at a time by approximately +/-20%, plus jointly relaxed and
jointly stringent scenarios. The binary geometry criterion is unchanged.
"""
from __future__ import annotations
import argparse
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm
from matplotlib.patches import Patch
from config import PROCESSED_DIR, FIGURE_DIR, load_parameters, ensure_directories

SCENARIOS = [
    ("Baseline", {}),
    ("Eligible months relaxed", {"minimum_months": 5}),
    ("Eligible months stringent", {"minimum_months": 7}),
    ("Raw RPI relaxed", {"raw_rpi_threshold": 0.92}),
    ("Raw RPI stringent", {"raw_rpi_threshold": 0.88}),
    ("Consensus residual relaxed", {"consensus_residual_pct": -8.0}),
    ("Consensus residual stringent", {"consensus_residual_pct": -12.0}),
    ("Monthly persistence relaxed", {"persistence_fraction": 0.40}),
    ("Monthly persistence stringent", {"persistence_fraction": 0.60}),
    ("LOBO power residual relaxed", {"lobo_q_residual_pct": -8.0}),
    ("LOBO power residual stringent", {"lobo_q_residual_pct": -12.0}),
    ("LOBO RPI residual relaxed", {"lobo_rpi_residual_pct": -8.0}),
    ("LOBO RPI residual stringent", {"lobo_rpi_residual_pct": -12.0}),
    ("Bootstrap upper relaxed", {"bootstrap_upper_pct": -4.0}),
    ("Bootstrap upper stringent", {"bootstrap_upper_pct": -6.0}),
    ("Lower-bound breach relaxed", {"lower_bound_breach_pct": 8.0}),
    ("Lower-bound breach stringent", {"lower_bound_breach_pct": 12.0}),
    ("All thresholds relaxed", {
        "minimum_months": 5, "raw_rpi_threshold": 0.92,
        "consensus_residual_pct": -8.0, "persistence_fraction": 0.40,
        "lobo_q_residual_pct": -8.0, "lobo_rpi_residual_pct": -8.0,
        "bootstrap_upper_pct": -4.0, "lower_bound_breach_pct": 8.0,
    }),
    ("All thresholds stringent", {
        "minimum_months": 7, "raw_rpi_threshold": 0.88,
        "consensus_residual_pct": -12.0, "persistence_fraction": 0.60,
        "lobo_q_residual_pct": -12.0, "lobo_rpi_residual_pct": -12.0,
        "bootstrap_upper_pct": -6.0, "lower_bound_breach_pct": 12.0,
    }),
]

def base_thresholds() -> dict:
    s = load_parameters()["screening"]
    return {
        "minimum_months": int(s["minimum_eligible_months"]),
        "raw_rpi_threshold": float(s["raw_relative_performance_threshold"]),
        "consensus_residual_pct": float(s["residual_threshold_pct"]),
        "persistence_fraction": float(s["persistence_fraction"]),
        "lobo_q_residual_pct": float(s["residual_threshold_pct"]),
        "lobo_rpi_residual_pct": float(s["residual_threshold_pct"]),
        "bootstrap_upper_pct": float(s["conservative_bootstrap_upper_limit_pct"]),
        "lower_bound_breach_pct": float(s["empirical_lower_bound_breach_pct"]),
    }

def choose_file(name: str) -> Path:
    base = PROCESSED_DIR / name
    regenerated = base.with_name(f"{base.stem}_regenerated{base.suffix}")
    return regenerated if regenerated.exists() else base

def load_inputs() -> pd.DataFrame:
    ranking = pd.read_csv(choose_file("04_consensus_bhe_ranking.csv"))
    lobo = pd.read_csv(choose_file("06_lobo_bhe_summary.csv"))
    keep = ["bhe", "median_monthly_resid_pct_Ridge", "persistence_lt10_Ridge",
            "median_monthly_resid_pct_LightGBM", "persistence_lt10_LightGBM"]
    return lobo.merge(ranking[keep], on="bhe", how="left", validate="one_to_one").sort_values("bhe")

def evaluate(df: pd.DataFrame, t: dict) -> pd.DataFrame:
    x = pd.DataFrame({"bhe": df["bhe"].astype(int)})
    x["minimum_evidence"] = df["eligible_months"] >= t["minimum_months"]
    x["raw_relative_performance"] = df["median_raw_rpi"] < t["raw_rpi_threshold"]
    x["model_consensus"] = ((df["median_monthly_resid_pct_Ridge"] <= t["consensus_residual_pct"]) &
                            (df["median_monthly_resid_pct_LightGBM"] <= t["consensus_residual_pct"]))
    # The archived consensus table stores persistence at the < -10% month definition;
    # sensitivity therefore perturbs the required fraction while retaining that event definition.
    x["monthly_persistence"] = ((df["persistence_lt10_Ridge"] >= t["persistence_fraction"]) &
                                (df["persistence_lt10_LightGBM"] >= t["persistence_fraction"]) &
                                (df["q_persistence_below_minus10"] >= t["persistence_fraction"]) &
                                (df["rpi_persistence_below_minus10"] >= t["persistence_fraction"]))
    x["lobo_thermal_power"] = df["median_monthly_q_resid_pct"] <= t["lobo_q_residual_pct"]
    x["lobo_relative_performance"] = df["median_monthly_rpi_resid_pct"] <= t["lobo_rpi_residual_pct"]
    x["bootstrap_uncertainty"] = ((df["q_bootstrap_CI_high_pct"] <= t["bootstrap_upper_pct"]) &
                                  (df["rpi_bootstrap_CI_high_pct"] <= t["bootstrap_upper_pct"]))
    x["empirical_interval_evidence"] = df["q_hourly_below_90PI_lower_pct"] >= t["lower_bound_breach_pct"]
    x["geometry_robustness"] = df["pipe_ablation_persistent"].fillna(False).astype(bool)
    cols = [c for c in x.columns if c != "bhe"]
    x["n_failed_criteria"] = (~x[cols]).sum(axis=1)
    x["candidate"] = x[cols].all(axis=1)
    return x

def main() -> None:
    ensure_directories()
    df = load_inputs()
    base = base_thresholds()
    rows, summaries = [], []
    for order, (name, overrides) in enumerate(SCENARIOS):
        th = base.copy(); th.update(overrides)
        ev = evaluate(df, th)
        ev.insert(0, "scenario_order", order); ev.insert(1, "scenario", name)
        rows.append(ev)
        cands = sorted(ev.loc[ev["candidate"], "bhe"].astype(int).tolist())
        summaries.append({"scenario_order": order, "scenario": name, "candidate_count": len(cands),
                          "candidate_bhes": ", ".join(map(str,cands)) if cands else "None"})
    long = pd.concat(rows, ignore_index=True)
    summary = pd.DataFrame(summaries)
    matrix_df = long.pivot(index="bhe", columns="scenario", values="candidate")[[n for n,_ in SCENARIOS]]
    suffix = ""
    long.to_csv(PROCESSED_DIR / f"R2_C1_threshold_sensitivity_all_bhes_long{suffix}.csv", index=False)
    summary.to_csv(PROCESSED_DIR / f"R2_C1_scenario_summary{suffix}.csv", index=False)
    matrix_df.astype(int).to_csv(PROCESSED_DIR / f"R2_C1_candidate_matrix{suffix}.csv")
    oat = [n for n,_ in SCENARIOS[1:17]]
    key=[]
    for bhe in [2,24,36,38]:
        sub=long[(long.bhe==bhe)&(long.scenario.isin(oat))]
        key.append({"bhe":bhe,"candidate_in_OAT_scenarios":int(sub.candidate.sum()),"OAT_scenarios_total":len(oat),
                    "OAT_stability_pct":100.0*float(sub.candidate.mean())})
    pd.DataFrame(key).to_csv(PROCESSED_DIR / f"R2_C1_key_BHE_stability{suffix}.csv", index=False)
    defs = pd.DataFrame([
        ["Minimum evidence", ">= 6 months", ">= 5 months", ">= 7 months"],
        ["Raw relative performance", "RPI < 0.90", "RPI < 0.92", "RPI < 0.88"],
        ["Model-consensus residual", "<= -10%", "<= -8%", "<= -12%"],
        ["Monthly persistence fraction", ">= 50%", ">= 40%", ">= 60%"],
        ["LOBO thermal-power residual", "<= -10%", "<= -8%", "<= -12%"],
        ["LOBO RPI residual", "<= -10%", "<= -8%", "<= -12%"],
        ["Bootstrap upper 95% CI", "<= -5%", "<= -4%", "<= -6%"],
        ["Empirical lower-bound breach", ">= 10%", ">= 8%", ">= 12%"],
        ["Geometry robustness", "persistent", "unchanged", "unchanged"],
    ], columns=["criterion","baseline","relaxed","stringent"])
    defs.to_csv(PROCESSED_DIR / f"R2_C1_threshold_definitions{suffix}.csv", index=False)

    ever = set(long.loc[long.candidate,"bhe"].astype(int)) | {2,24,36,38}
    bhes=sorted(ever); names=[n for n,_ in SCENARIOS]
    m=np.zeros((len(bhes),len(names)),dtype=int)
    for i,bhe in enumerate(bhes):
        s=long[long.bhe==bhe].set_index("scenario")["candidate"]
        m[i,:]=[2 if bool(s[n]) else 0 for n in names]
    if 2 in bhes: m[bhes.index(2),0]=1
    labels=[n.replace(' ', '\n', 1) if n!='Baseline' else n for n in names]
    fig,ax=plt.subplots(figsize=(17,6.2))
    cmap=ListedColormap(["#F7F7F7","#B8B8B8","#2F6F8F"]); norm=BoundaryNorm([-0.5,0.5,1.5,2.5],3)
    ax.imshow(m,aspect="auto",cmap=cmap,norm=norm,interpolation="nearest")
    ax.set_yticks(range(len(bhes))); ax.set_yticklabels([f"BHE {b}" for b in bhes],fontsize=11.5)
    ax.set_xticks(range(len(labels))); ax.set_xticklabels(labels,rotation=38,ha="right",rotation_mode="anchor",fontsize=9.2)
    ax.set_xlabel("Threshold-sensitivity scenario",fontsize=11.5,labelpad=12); ax.set_ylabel("BHE circuit",fontsize=11.5,labelpad=10)
    # No in-figure title: the manuscript caption provides the title/context.
    ax.set_xticks(np.arange(-0.5,len(labels),1),minor=True); ax.set_yticks(np.arange(-0.5,len(bhes),1),minor=True)
    ax.grid(which="minor",color="white",linewidth=1.2); ax.tick_params(which="minor",bottom=False,left=False)
    ax.tick_params(axis="x",which="major",pad=7,length=0); ax.tick_params(axis="y",which="major",length=0)
    for xpos in [0.5,16.5]: ax.axvline(xpos,color="#6E6E6E",linewidth=1.25,alpha=0.75)
    for i in range(len(bhes)):
        for j in range(len(labels)):
            if m[i,j]==2: ax.text(j,i,"C",ha="center",va="center",fontsize=10.5,color="white",fontweight="bold")
            elif m[i,j]==1: ax.text(j,i,"B",ha="center",va="center",fontsize=10.5,color="black",fontweight="bold")
    ax.legend(handles=[Patch(facecolor="#2F6F8F",label="C: candidate"),Patch(facecolor="#B8B8B8",label="B: manuscript borderline (baseline)"),Patch(facecolor="#F7F7F7",edgecolor="#A0A0A0",label="Not classified as candidate")],
              loc="lower center",bbox_to_anchor=(0.5,1.015),ncol=3,frameon=False,fontsize=9.8)
    ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False)
    fig.subplots_adjust(left=0.085,right=0.995,top=0.88,bottom=0.34)
    fig.savefig(FIGURE_DIR/"Fig06_threshold_sensitivity.png",dpi=600,bbox_inches="tight",pad_inches=0.08)
    fig.savefig(FIGURE_DIR/"Fig06_threshold_sensitivity.pdf",bbox_inches="tight",pad_inches=0.08)
    plt.close(fig)
    print(summary.to_string(index=False))

if __name__ == "__main__": main()
